Update docs
yiisoft/db-sphinx pull request #41
Opened 2024-05-11 09:05 UTC by luizcmarin

2024-05-18 16:57 UTC, vjik requested changes

2024-05-18 16:57 UTC, vjik commented on docs/guide/pt-BR/basic-usage.md
Translate to pt-BR or remove this translation

2024-05-19 08:38 UTC, luizcmarin commented on docs/guide/pt-BR/basic-usage.md
![image](https://github.com/yiisoft/db-sphinx/assets/67489841/0ed6ebe7-dc20-4d8d-88f8-2f8884f80024)

2024-05-19 14:04 UTC, vjik commented on docs/guide/pt-BR/basic-usage.md
Close non-actual PRs.

2024-05-19 14:04 UTC, closed without merging